server:
  port: 8080
spring:
  application:
    name: java-backend-template
  profiles:
    active: local
management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show:
        details: always
  metrics:
    tags:
      application: ${spring.application.name}